TrajectoryPlannerROS:
  max_vel_x: 1.0
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.2

  acc_lim_theta: 1.5
  acc_lim_x: 1.0
  acc_lim_y: 1.0

  holonomic_robot: true
  meter_scoring: true
