obstacle_range: 4
raytrace_range: 5

robot_radius: 0.9
inflation_radius: 0.95

observation_sources: point_cloud_publisher point_cloud2_publisher

point_cloud_publisher: {sensor_frame: m100_guidance, data_type: PointCloud, topic: cloud, marking: true, clearing: true}

point_cloud2_publisher: {sensor_frame: m100_guidance, data_type: PointCloud2, topic: /stereo/points2, marking: true, clearing: true, obstacle_range: 4, raytrace_range: 5}
