local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 5.0
  publish_frequency: 1.0

  static_map: false
  rolling_window: true

  width: 8
  height: 8
  resolution: 0.1

