#include "Edge.h"
#include "floatImage.h"
#include "gLine2D.h"
//#include "GLineSegment2D.h"
#include "gaussian.h"
//#include "GrayModel.h"
//#include "Gridder.h"
#include "homography33.h"
#include "mathUtil.h"
//#include "Quad.h"
//#include "Segment.h"
//#include "TagDetection.h"
//#include "TagDetector.h"
//#include "TagFamily.h"
#include "UnionFindSimple.h"
#include "XYWeight.h"

